### ISSUE TITLE
TTS Keyboard echo

### ISSUE THREAD

**Issue by zz1616611** [joelpurra/talkie#12]
hope to support
always speak typed keys
speak phonetic letters
phonetic letters are spoken when long pressing on
keyboard keys and navigating
by character.
For learning langusges    0.0

**Comment by joelpurra** [comment]
@zz1616611: thanks for the suggestions!

It would be nice to speak typed keys, at least for languages which use logograms. I don't personally speak any of those languages though, so will see if Talkie is the right place to implement it.
https://en.wikipedia.org/wiki/Logogram

It would also be nice to have keyboard navigation for reading the selected text, so it's easy to step back and forth in the characters/words. It is quite an advanced feature though. Might be tricky to implement visually (highlighting the text being read) on all websites though, as websites all look different.

Both of these suggestions could perhaps be implemented as a separate text input box in Talkie. There is already a test in the language/voice settings page. It is not very automatic, but perhaps you can try it first? Does it work similar to what you had in mind?

I will keep these suggestions in mind for future versions of Talkie and Talkie Premium. There is no concrete timeline though, as other work has higher priority, so I will close this suggestion issue for now. Thank you again for the suggestions, and feel free to reply =)

**Comment by Pantyhose-X** [comment]
> @zz1616611: thanks for the suggestions!
> 
> It would be nice to speak typed keys, at least for languages which use logograms. I don't personally speak any of those languages though, so will see if Talkie is the right place to implement it.
> https://en.wikipedia.org/wiki/Logogram
> 
> It would also be nice to have keyboard navigation for reading the selected text, so it's easy to step back and forth in the characters/words. It is quite an advanced feature though. Might be tricky to implement visually (highlighting the text being read) on all websites though, as websites all look different.
> 
> Both of these suggestions could perhaps be implemented as a separate text input box in Talkie. There is already a test in the language/voice settings page. It is not very automatic, but perhaps you can try it first? Does it work similar to what you had in mind?
> 
> I will keep these suggestions in mind for future versions of Talkie and Talkie Premium. There is no concrete timeline though, as other work has higher priority, so I will close this suggestion issue for now. Thank you again for the suggestions, and feel free to reply =)

Applied to language learning. Pronunciation correction
Always speak typed keys Speak phonetic letters Phonetic letters are spoken when long pressing on keyboard keys and navigating by character.

* example
* https://www.youtube.com/watch?v=YPBn6D6pf78&feature=youtu.be&t=213
