### ISSUE TITLE
How to run the application on my machine

### ISSUE THREAD

**Issue by PrathamDogra** [joelpurra/talkie#19]
Hi Joel I want to run this application on my laptop but couldn't find the proper steps to do so. Can you brief me a little on how to set up the application on my laptop?

**Comment by joelpurra** [comment]
@PrathamDogra: perhaps the documentation needs an update. Which lines in the `*.md` files are unclear to you?

**Comment by PrathamDogra** [comment]
I don't know how to load package folders as an unpacked extension. My package folders are empty after installation.

**Comment by joelpurra** [comment]
@PrathamDogra: did you build the project first?

https://github.com/joelpurra/talkie/blob/v6.0.1/DEVELOP.md#L57

If you did, were there any errors?

**Comment by PrathamDogra** [comment]
Issue resolved. I used the Ubuntu terminal( WSL) to run the application.

**Comment by joelpurra** [comment]
@PrathamDogra: oh, didn't know you are using Windows. Development on Windows is not (officially) supported, but glad to hear that using WSL works!

- https://github.com/joelpurra/talkie/blob/v6.0.1/DEVELOP.md#L30-L31
- https://en.wikipedia.org/wiki/Windows_Subsystem_for_Linux
