### ISSUE TITLE
Doesn't work on the selected speaker (bluetooth, different sound outputs, windows 11), works on another output

### ISSUE THREAD

**Issue by Helmut-Ortmann** [joelpurra/talkie#23]
_Please fill out the following to help us help you. Replace `...` with your own values, where applicable._

### Expected behavior
It uses the speaker currently configured in Windows
...

### Actual behavior
It uses another speaker than the configured speaker. Other apps are working as expected.
...

### Steps to reproduce behavior
1. User: Read text
2. Windows: Uses the wrong sound device
3. User: Change the  sound device
4. Windows outputs to another sound device

Remark: Usually I use Bluetooth. I can output to Bluetooth but have to choose another device. The sound devices seem to be shifted. With other Chrom or Windows applications the sound goes to the correct sound device.
...

### Website

- Website the problem occurred on: ...
- If possible, include the full link: ...

not relevant

### Text and language

- Which part of the website did you want spoken: ...
- If possible, include the full text: ...
- Language the text was expected to be spoken in: ...

not relevant

### System information

- Your browser: ... Chrom
- Your browser version: ... Version 96.0.4664.110
- Your operating system: Windows 11
- Your operating system version: 

### Additional information

...

**Comment by joelpurra** [comment]
@Helmut-Ortmann: Talkie has no way of controlling which audio device to use; Talkie can only tell the browser to "start/stop speaking text". This is therefore not a Talkie issue, but a system configuration issue.

General debugging tips:

- Audio device selection is up to the browser and operating system, so check all settings there first.
- You may need to restart your browser if you change the audio device, in case the browser's TTS already locked in to some specific audio device. Again, this is out of control for Talkie.
- Some speakers I personally use are slow to start, so have to "wake them up" by playing some sound first. This is not usually noticeable when playing music/videos, but may be with TTS.
- Confirm that the volume is not too low. There are several places to check -- the physical audio device, system audio settings, browser application audio settings.

Good luck with setting up the sound! Closing this issue as out of scope.
