### ISSUE TITLE
How Can I Set the Speed?

### ISSUE THREAD

**Issue by YingHN** [joelpurra/talkie#33]
I have got the Pre,but I can't find the button which can help me change the speed.
**where is it?** If it is not allow to use at that time(2020/8/13)? 
I use *Chrome* and I install this in the google store.
I promise **I have not change any code of it**.

**Comment by Nathan903** [comment]
go to chrome://extensions --> Talkie --> Extension options --> Voices --> Language --> [choose a voice] --> change speed

**Comment by joelpurra** [comment]
Closing as answered.
