### ISSUE TITLE
add the ability to set the voice set

### ISSUE THREAD

**Issue by Goddard** [joelpurra/talkie#4]
Not sure if this is possible, but I am not able to set the voice set I want to use.  Using 2.0.2 in Chrome.

**Comment by joelpurra** [comment]
@Goddard: no, it's not possible at the moment. Currently the language of the text/page is detected automatically, then passed to the browser. The browser picks a voice out of the available ones for that language.

My impression is that the automatic mode works pretty well (at least in chrome). Have thought of adding voice overrides though, and started preparing for it. It'd require some work to make a configuration interface and override the language/voice selection logic, so am thinking of making it a paid feature (as noted in the readme) when installed through the chrome web store. Planning to keep the software open source, but this would support spending time on adding advanced features. What do you think?

It's on the todo-list, so I'll leave this issue open.

**Comment by joelpurra** [comment]
@Goddard: voice selection has now been implemented in Talkie Premium! You can select your favorite voice per language even. You can test the feature in regular Talkie, build from Talkie Premium from source, or get it from the stores.

- https://chrome.google.com/webstore/detail/talkie-premium/madmpgibncancdmkjflnifcdakndkngo
- https://addons.mozilla.org/en-US/firefox/addon/talkie-premium/

What do you think, does it work as you'd prefer?
